//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFronteranet.Gc
{
    using ITela.Gc;
    
    
    /// <summary>
    /// 
    /// </summary>
    [GcMetadata("https://raw.githubusercontent.com/ericdes/tela-interface/master/gc/CountryCode-01" +
        ".gc", IsRestriction=true)]
    [GcEnumField("Alpha2Code", GcEnumPart.Code, DataType="CountryCode", Min=2, Max=2)]
    [GcEnumField("Name", GcEnumPart.Value, GcEnumPart.Comments, DataType="Name", Min=1, Max=50)]
    public enum Country
    {
        
        /// <summary>
        /// United States
        /// </summary>
        [GcCodeValue("US", "United States")]
        US,
        
        /// <summary>
        /// Mexico
        /// </summary>
        [GcCodeValue("MX", "Mexico")]
        MX,
        
        /// <summary>
        /// Canada
        /// </summary>
        [GcCodeValue("CA", "Canada")]
        CA,
    }
}
