//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontera.Base
{
    using ITela.Gc;
    
    
    /// <summary>
    /// 
    /// </summary>
    [GcMetadata("http://docs.oasis-open.org/ubl/os-UBL-2.1/cl/gc/default/TransportEquipmentTypeCod" +
        "e-2.1.gc", IsRestriction=true)]
    [GcEnumField("code", GcEnumPart.Code, DataType="Code", Min=1, Max=20)]
    [GcEnumField("name", GcEnumPart.Value, GcEnumPart.Comments, DataType="Description", Min=1, Max=100)]
    [GcEnumField("description", GcEnumPart.CommentsAdditional, DataType="Memo", Min=1, Max=1000)]
    public enum TransportEquipmentType
    {
        
        /// <summary>
        /// Slipsheet
        /// A cardboard platform used for holding product for storage or transportation.
        /// </summary>
        [GcCodeValue("AG", "Slipsheet")]
        Slipsheet,
        
        /// <summary>
        /// Roller Cage
        /// Wheeled wire cage.
        /// </summary>
        [GcCodeValue("BPT", "Roller Cage")]
        RollerCage,
        
        /// <summary>
        /// Out of bag parcel
        /// Postal item which is conveyed individually, with only the wrapping provided by the mailer for protection.
        /// </summary>
        [GcCodeValue("BPV", "Out of bag parcel")]
        Wrapping,
        
        /// <summary>
        /// Container
        /// Equipment item as defined by ISO for transport. It must be of: A) permanent character, strong enough for repeated use; B) designed to facilitate the carriage of goods, by one or more modes of transport, without intermediate reloading; C) fitted with devices for its ready handling, particularly.
        /// </summary>
        [GcCodeValue("CN", "Container")]
        Container,
        
        /// <summary>
        /// Pallet
        /// A platform on which goods can be stacked in order to facilitate the movement by a forklift or sling.
        /// </summary>
        [GcCodeValue("PA", "Pallet")]
        Pallet,
        
        /// <summary>
        /// Platform
        /// A piece of equipment normally having a flat surface, or prepared for carrying cargo with a specific shape.
        /// </summary>
        [GcCodeValue("PL", "Platform")]
        Platform,
        
        /// <summary>
        /// Trailer
        /// A vehicle without motive power, designed for the carriage of cargo and to be towed by a motor vehicle.
        /// </summary>
        [GcCodeValue("TE", "Trailer")]
        Trailer,
        
        /// <summary>
        /// ULD (Unit load device)
        /// An aircraft container or pallet.
        /// </summary>
        [GcCodeValue("UL", "ULD (Unit load device)")]
        AircraftContainer,
    }
}
