//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFronteranet.Gc.Data
{
    using ITela.Gc;
    
    
    /// <summary>
    /// 
    /// </summary>
    [GcMetadata("https://raw.githubusercontent.com/ericdes/fronteranet-interface/master/IFronteran" +
        "et.Gc.Data/gc-frontera/AllowanceChargeReasonCode-1.0.gc", IsRestriction=false)]
    public enum AllowanceChargeReasonCode
    {
        
        /// <summary>
        /// Minimum charge applied
        /// </summary>
        [GcCodeValue("MinimumCharge", "Minimum charge applied")]
        MinimumCharge,
    }
}
