//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFronteranet.Gc.Data
{
    using ITela.Gc;
    
    
    /// <summary>
    /// 
    /// </summary>
    [GcMetadata("https://raw.githubusercontent.com/ericdes/fronteranet-interface/master/IFronteran" +
        "et.Gc.Data/gc-frontera/AllowanceChargeID-1.0.gc", IsRestriction=false)]
    public enum AllowanceCharge
    {
        
        /// <summary>
        /// Crossing or Mexican side Expenses
        /// </summary>
        [GcCodeValue("CrossExpMe", "Crossing or Mexican side Expenses")]
        MexicanBorderCrossingExpense,
        
        /// <summary>
        /// Extra Stop
        /// </summary>
        [GcCodeValue("ExtraStop", "Extra Stop")]
        ExtraStop,
        
        /// <summary>
        /// Handling
        /// </summary>
        [GcCodeValue("H", "Handling")]
        Handling,
        
        /// <summary>
        /// Warehouse space
        /// </summary>
        [GcCodeValue("Space", "Warehouse space")]
        WarehouseSpace,
        
        /// <summary>
        /// Storage / Day
        /// </summary>
        [GcCodeValue("Storage", "Storage / Day")]
        StoragePerDay,
        
        /// <summary>
        /// Minimum charge to apply
        /// </summary>
        [GcCodeValue("MinimumCharge", "Minimum charge to apply")]
        MinimumChargeToApply,
    }
}
