//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFronteranet.Gc.Data
{
    using ITela.Gc;
    
    
    /// <summary>
    /// 
    /// </summary>
    [GcMetadata("http://docs.oasis-open.org/ubl/os-UBL-2.1/cl/gc/default/CurrencyCode-2.1.gc", IsRestriction=true)]
    [GcEnumField("code", GcEnumPart.Code, DataType="CurrencyCode", Min=3, Max=3)]
    [GcEnumField("name", GcEnumPart.Value, GcEnumPart.Comments, DataType="Description", Min=3, Max=65)]
    public enum Currency
    {
        
        /// <summary>
        /// US Dollar
        /// </summary>
        [GcCodeValue("USD", "US Dollar")]
        USD,
    }
}
