//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFronteranet.Gc.Data
{
    using ITela.Gc;
    
    
    /// <summary>
    /// 
    /// </summary>
    public enum OrganisationIDType
    {
        
        /// <summary>
        /// Frontera Office v.1 Contact Identifier
        /// </summary>
        FOv1,
    }
}
