//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFronteranet.Gc.Data
{
    using ITela.Gc;
    
    
    /// <summary>
    /// 
    /// </summary>
    public enum OrganisationNameElementType
    {
        
        /// <summary>
        /// "Sakthisoft" in "Sakthisoft Pty. Ltd". "Pty.Ltd" is the legal entity for the organisation name "Sakthisoft"
        /// </summary>
        NameOnly,
        
        /// <summary>
        /// Full name of the organisation. e.g. Sakthisoft Pty. Ltd
        /// </summary>
        FullName,
    }
}
