//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFronteranet.Gc.Data
{
    using ITela.Gc;
    
    
    /// <summary>
    /// 
    /// </summary>
    [GcMetadata("https://raw.githubusercontent.com/ericdes/fronteranet-interface/master/IFronteran" +
        "et.Gc.Data/gc-frontera/PriceTypeCode-1.0.gc", IsRestriction=false)]
    public enum PriceType
    {
        
        /// <summary>
        /// Plan 1
        /// </summary>
        [GcCodeValue("1", "Plan 1")]
        Plan1,
        
        /// <summary>
        /// Plan 2A
        /// </summary>
        [GcCodeValue("2A", "Plan 2A")]
        Plan2A,
        
        /// <summary>
        /// Plan 2B
        /// </summary>
        [GcCodeValue("2B", "Plan 2B")]
        Plan2B,
    }
}
